import { FichaTecnicaFields } from "../types/Estadistica";

export const FICHA_FIELDS_MAP: Record<string, keyof FichaTecnicaFields> = {
  nombre_del_indicador_o_estadistica_ambiental: "nombre",
  finalidad: "finalidad",
  descripcion_definicion: "descripcion",
  unidad_de_medida: "unidadMedida",
  formula_calculo: "formulaCalculo",
  formula_de_calculo: "formulaCalculo",
  metodologia_calculo: "metodologiaCalculo",
  metodologia_de_calculo: "metodologiaCalculo",
  fuente: "fuente",
  unidad_organica_generadora: "unidadOrganicaGeneradora",
  url: "url",
  periodicidad_de_generacion_de_la_informacion_por_la_entidad: "periodicidadGeneracion",
  periodicidad_de_entrega_registro_de_la_informacion_por_la_entidad: "periodicidadEntrega",
  periodo_serie_tiempo: "periodoSerieTiempo",
  periodo_de_serie_tiempo: "periodoSerieTiempo",
  periodo_de_serie_de_tiempo: "periodoSerieTiempo",
  ambito_geografico: "ambitoGeografico",
  limitaciones: "limitaciones",
  relacion_con_objetivos_de_politica: "relacionObjetivosNacionales",
  "relacion_con_objetivos_de_politica,_normas,_metas_ambientales_nacionales": "relacionObjetivosNacionales",
  relacion_con_iniciativas_internacionales: "relacionIniciativasInternacionales",
  correo_electronico: "correoElectronico",
  datos_del_contacto: "datosContacto",
  telefono_celular: "telefonoCelular",
  clasificacion_mdea: "clasificacionMdea",
  mdea: "clasificacionMdea",
  clasificacion_ods: "clasificacionOds",
  ods: "clasificacionOds",
  clasificacion_ocde: "clasificacionOcde",
  ocde: "clasificacionOcde",
  clasificacion_pna: "clasificacionPna",
  pna: "clasificacionPna",
};
