image: node:20

stages:
  - release

# Ejecutar semantic-release para el versionado automático
release:
  stage: release
  script:
    - npm install --global semantic-release
    - npm install --global @semantic-release/git @semantic-release/changelog -D
    - npx semantic-release
