image: node:20

stages:
  - release

# Ejecutar semantic-release para el versionado automático
release:
  stage: release
  script:
    - npm install --global semantic-release
    - npm install --global @semantic-release/gitlab @semantic-release/changelog @semantic-release/git -D
    - npx semantic-release
